name: env_clim
channels:
  - conda-forge
  - defaults

dependencies:
  - matplotlib=3.7.2
  - python=3.11.5
  - pandas=2.0.3
  - numpy
  - requests-cache
  - pip
  - ipykernel
  - scikit-learn
  - pip:
      - openmeteo-requests
      - retry-requests
